changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
      regex: '^feat[:(]'
    - title: 🐛 Bug Fixes
      labels:
        - bug
      regex: '^fix[:(]'
    - title: 📦 Dependencies
      labels:
        - dependencies
      regex: '^[a-z]+\((deps|dev-deps)\)[:]'
    - title: Other Changes
      regex: '^.*$'
