name: pull request
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm i --frozen-lockfile
      - run: npm run lint
