name: publish npm

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  deploy_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds
      - uses: actions/checkout@v7.0.0
      - name: Publish NPM
        run: npm publish

